name: build

on:
  pull_request:
  push:
  schedule:
    # once a day at 8
    - cron: "0 8 * * *"

jobs:
  build:
    runs-on: ubuntu-latest
    timeout-minutes: 10

    steps:
      # Checks out to the current directory.
      - uses: actions/checkout@v2
        with:
          fetch-depth: 1
          repository: mozilla/mozjpeg

      - name: Run ls
        run: ls

      - name: Install tooling from Apt
        run: sudo apt-get install awscli cmake nasm make

      - name: CMake
        run: cmake -G"Unix Makefiles" .

      - name: Make
        run: make

      - name: Make Debian package
        run: make deb

      - uses: actions/upload-artifact@v1
        with:
          name: mozjpeg.deb

          # TODO: Obviously this breaks on the next major version release.
          path: ./mozjpeg_4.0.0_amd64.deb

      # Relies on the following secrets from GitHub's GUI configuration:
      #
      #     AWS_ACCESS_KEY_ID
      #     AWS_SECRET_ACCESS_KEY
      #
      # They use a specific AWS user whose access is only allowed to this one
      # S3 bucket.
      - name: Upload to S3
        run: aws s3 cp mozjpeg_*_amd64.deb s3://mozjpeg-brandur/
        env:
          AWS_ACCESS_KEY_ID: ${{ secrets.AWSAccessKeyID }}
          AWS_SECRET_ACCESS_KEY: ${{ secrets.AWSSecretAccessKey }}
        if: github.ref == 'refs/heads/master'
