name: build

on:
  pull_request:
  push:
  schedule:
    # once a day at 8
    - cron: "0 8 * * *"

jobs:
  build:
    runs-on: ubuntu-latest
    timeout-minutes: 10

    steps:
      # Checks out to the current directory.
      - uses: actions/checkout@v2
        with:
          fetch-depth: 1
          repository: mozilla/mozjpeg

      - name: Run ls
        run: ls

      - name: Install tooling from Apt
        run: sudo apt-get install cmake nasm make

      - name: CMake
        run: cmake -G"Unix Makefiles" .

      - name: Make
        run: make

      - name: Make Debian package
        run: make deb

      - uses: actions/upload-artifact@v1
        with:
          name: mozjpeg.deb

          # TODO: Obviously this breaks on the next major version release.
          path: ./mozjpeg_4.0.0_amd64.deb
